[package]
name = "dex"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
dex_contract = "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c"
# deployer = "_"

[dev-addresses]
dex_contract = "0xAA"
# deployer = "0xBB"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[dev-dependencies]
